# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BugReproducerAssistant.ui'
#
# Created: Tue Sep 20 11:42:40 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BugReproducerAssistant(object):
    def setupUi(self, BugReproducerAssistant):
        BugReproducerAssistant.setObjectName(_fromUtf8("BugReproducerAssistant"))
        BugReproducerAssistant.setWindowModality(QtCore.Qt.ApplicationModal)
        BugReproducerAssistant.resize(1264, 643)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BugReproducerAssistant.sizePolicy().hasHeightForWidth())
        BugReproducerAssistant.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("C:/Users/Gerva/.designer/images/icon.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BugReproducerAssistant.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(BugReproducerAssistant)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.explorersTab = QtGui.QTabWidget(self.centralwidget)
        self.explorersTab.setGeometry(QtCore.QRect(10, 60, 381, 391))
        self.explorersTab.setObjectName(_fromUtf8("explorersTab"))
        self.projectExplorerTab = QtGui.QWidget()
        self.projectExplorerTab.setObjectName(_fromUtf8("projectExplorerTab"))
        self.projectExplorerTreeWidget = QtGui.QTreeWidget(self.projectExplorerTab)
        self.projectExplorerTreeWidget.setGeometry(QtCore.QRect(0, 40, 381, 561))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.projectExplorerTreeWidget.setFont(font)
        self.projectExplorerTreeWidget.setObjectName(_fromUtf8("projectExplorerTreeWidget"))
        self.projectExplorerTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.projectExplorerTreeWidget.header().setVisible(False)
        self.layoutWidget = QtGui.QWidget(self.projectExplorerTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 96, 42))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.addFileButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addFileButton.sizePolicy().hasHeightForWidth())
        self.addFileButton.setSizePolicy(sizePolicy)
        self.addFileButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("images/text-x-source.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addFileButton.setIcon(icon1)
        self.addFileButton.setIconSize(QtCore.QSize(32, 32))
        self.addFileButton.setObjectName(_fromUtf8("addFileButton"))
        self.horizontalLayout.addWidget(self.addFileButton)
        self.explorersTab.addTab(self.projectExplorerTab, _fromUtf8(""))
        self.executionsTab = QtGui.QWidget()
        self.executionsTab.setObjectName(_fromUtf8("executionsTab"))
        self.executionsExplorerTreeWidget = QtGui.QTreeWidget(self.executionsTab)
        self.executionsExplorerTreeWidget.setGeometry(QtCore.QRect(0, 70, 371, 531))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.executionsExplorerTreeWidget.setFont(font)
        self.executionsExplorerTreeWidget.setObjectName(_fromUtf8("executionsExplorerTreeWidget"))
        self.executionsExplorerTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.executionsExplorerTreeWidget.header().setVisible(False)
        self.compileProgramButton = QtGui.QPushButton(self.executionsTab)
        self.compileProgramButton.setGeometry(QtCore.QRect(10, 0, 44, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.compileProgramButton.sizePolicy().hasHeightForWidth())
        self.compileProgramButton.setSizePolicy(sizePolicy)
        self.compileProgramButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("images/run-build-file-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.compileProgramButton.setIcon(icon2)
        self.compileProgramButton.setIconSize(QtCore.QSize(32, 32))
        self.compileProgramButton.setObjectName(_fromUtf8("compileProgramButton"))
        self.executeProgramButton = QtGui.QPushButton(self.executionsTab)
        self.executeProgramButton.setGeometry(QtCore.QRect(60, 0, 44, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.executeProgramButton.sizePolicy().hasHeightForWidth())
        self.executeProgramButton.setSizePolicy(sizePolicy)
        self.executeProgramButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("images/system-run.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.executeProgramButton.setIcon(icon3)
        self.executeProgramButton.setIconSize(QtCore.QSize(32, 32))
        self.executeProgramButton.setObjectName(_fromUtf8("executeProgramButton"))
        self.generateEquivalentProgramButton = QtGui.QPushButton(self.executionsTab)
        self.generateEquivalentProgramButton.setGeometry(QtCore.QRect(110, 0, 44, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generateEquivalentProgramButton.sizePolicy().hasHeightForWidth())
        self.generateEquivalentProgramButton.setSizePolicy(sizePolicy)
        self.generateEquivalentProgramButton.setText(_fromUtf8(""))
        self.generateEquivalentProgramButton.setIcon(icon1)
        self.generateEquivalentProgramButton.setIconSize(QtCore.QSize(32, 32))
        self.generateEquivalentProgramButton.setObjectName(_fromUtf8("generateEquivalentProgramButton"))
        self.unitTestRadioButton = QtGui.QRadioButton(self.executionsTab)
        self.unitTestRadioButton.setGeometry(QtCore.QRect(210, 30, 82, 16))
        self.unitTestRadioButton.setObjectName(_fromUtf8("unitTestRadioButton"))
        self.label_2 = QtGui.QLabel(self.executionsTab)
        self.label_2.setGeometry(QtCore.QRect(200, 10, 171, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.explorersTab.addTab(self.executionsTab, _fromUtf8(""))
        self.codeTextEdit = QtGui.QTextEdit(self.centralwidget)
        self.codeTextEdit.setGeometry(QtCore.QRect(390, 20, 861, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.codeTextEdit.setFont(font)
        self.codeTextEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.codeTextEdit.setObjectName(_fromUtf8("codeTextEdit"))
        self.outputWindowTextEdit = QtGui.QPlainTextEdit(self.centralwidget)
        self.outputWindowTextEdit.setEnabled(True)
        self.outputWindowTextEdit.setGeometry(QtCore.QRect(0, 510, 1251, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.outputWindowTextEdit.setFont(font)
        self.outputWindowTextEdit.setReadOnly(True)
        self.outputWindowTextEdit.setObjectName(_fromUtf8("outputWindowTextEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 490, 46, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.refreshProjectButton = QtGui.QPushButton(self.centralwidget)
        self.refreshProjectButton.setGeometry(QtCore.QRect(300, 10, 51, 41))
        self.refreshProjectButton.setMouseTracking(False)
        self.refreshProjectButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("images/view-refresh-5.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshProjectButton.setIcon(icon4)
        self.refreshProjectButton.setIconSize(QtCore.QSize(32, 32))
        self.refreshProjectButton.setCheckable(False)
        self.refreshProjectButton.setDefault(False)
        self.refreshProjectButton.setObjectName(_fromUtf8("refreshProjectButton"))
        self.clearOutputButton = QtGui.QPushButton(self.centralwidget)
        self.clearOutputButton.setGeometry(QtCore.QRect(60, 470, 44, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clearOutputButton.sizePolicy().hasHeightForWidth())
        self.clearOutputButton.setSizePolicy(sizePolicy)
        self.clearOutputButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("images/edit-clear-3.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearOutputButton.setIcon(icon5)
        self.clearOutputButton.setIconSize(QtCore.QSize(32, 32))
        self.clearOutputButton.setObjectName(_fromUtf8("clearOutputButton"))
        self.openProjectButton = QtGui.QPushButton(self.centralwidget)
        self.openProjectButton.setGeometry(QtCore.QRect(70, 10, 51, 41))
        self.openProjectButton.setMouseTracking(False)
        self.openProjectButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("images/document-open-5.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openProjectButton.setIcon(icon6)
        self.openProjectButton.setIconSize(QtCore.QSize(32, 32))
        self.openProjectButton.setCheckable(False)
        self.openProjectButton.setDefault(False)
        self.openProjectButton.setObjectName(_fromUtf8("openProjectButton"))
        self.newProjectButton = QtGui.QPushButton(self.centralwidget)
        self.newProjectButton.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.newProjectButton.setMouseTracking(False)
        self.newProjectButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("images/document-new-5.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newProjectButton.setIcon(icon7)
        self.newProjectButton.setIconSize(QtCore.QSize(32, 32))
        self.newProjectButton.setCheckable(False)
        self.newProjectButton.setDefault(False)
        self.newProjectButton.setObjectName(_fromUtf8("newProjectButton"))
        self.closeProjectButton = QtGui.QPushButton(self.centralwidget)
        self.closeProjectButton.setGeometry(QtCore.QRect(190, 10, 51, 41))
        self.closeProjectButton.setMouseTracking(False)
        self.closeProjectButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("images/document-close-2.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeProjectButton.setIcon(icon8)
        self.closeProjectButton.setIconSize(QtCore.QSize(32, 32))
        self.closeProjectButton.setCheckable(False)
        self.closeProjectButton.setDefault(False)
        self.closeProjectButton.setObjectName(_fromUtf8("closeProjectButton"))
        self.editProjectButton = QtGui.QPushButton(self.centralwidget)
        self.editProjectButton.setGeometry(QtCore.QRect(130, 10, 51, 41))
        self.editProjectButton.setMouseTracking(False)
        self.editProjectButton.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("images/edit-4.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editProjectButton.setIcon(icon9)
        self.editProjectButton.setIconSize(QtCore.QSize(32, 32))
        self.editProjectButton.setCheckable(False)
        self.editProjectButton.setDefault(False)
        self.editProjectButton.setObjectName(_fromUtf8("editProjectButton"))
        BugReproducerAssistant.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BugReproducerAssistant)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1264, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuHerramientas = QtGui.QMenu(self.menubar)
        self.menuHerramientas.setObjectName(_fromUtf8("menuHerramientas"))
        BugReproducerAssistant.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BugReproducerAssistant)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BugReproducerAssistant.setStatusBar(self.statusbar)
        self.actionNewProject = QtGui.QAction(BugReproducerAssistant)
        self.actionNewProject.setIcon(icon7)
        self.actionNewProject.setObjectName(_fromUtf8("actionNewProject"))
        self.actionOpenProject = QtGui.QAction(BugReproducerAssistant)
        self.actionOpenProject.setIcon(icon6)
        self.actionOpenProject.setObjectName(_fromUtf8("actionOpenProject"))
        self.actionCloseProject = QtGui.QAction(BugReproducerAssistant)
        self.actionCloseProject.setIcon(icon8)
        self.actionCloseProject.setObjectName(_fromUtf8("actionCloseProject"))
        self.actionExit = QtGui.QAction(BugReproducerAssistant)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionBraHelp = QtGui.QAction(BugReproducerAssistant)
        self.actionBraHelp.setObjectName(_fromUtf8("actionBraHelp"))
        self.actionAbout = QtGui.QAction(BugReproducerAssistant)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionOptions = QtGui.QAction(BugReproducerAssistant)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionEditProject = QtGui.QAction(BugReproducerAssistant)
        self.actionEditProject.setIcon(icon9)
        self.actionEditProject.setObjectName(_fromUtf8("actionEditProject"))
        self.menuFile.addAction(self.actionNewProject)
        self.menuFile.addAction(self.actionOpenProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionEditProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCloseProject)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionBraHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHerramientas.addAction(self.actionOptions)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHerramientas.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BugReproducerAssistant)
        self.explorersTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BugReproducerAssistant)

    def retranslateUi(self, BugReproducerAssistant):
        BugReproducerAssistant.setWindowTitle(QtGui.QApplication.translate("BugReproducerAssistant", "Bug-reproducer Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.addFileButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Agregar archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.explorersTab.setTabText(self.explorersTab.indexOf(self.projectExplorerTab), QtGui.QApplication.translate("BugReproducerAssistant", "Explorador de proyectos", None, QtGui.QApplication.UnicodeUTF8))
        self.compileProgramButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Compilar programa", None, QtGui.QApplication.UnicodeUTF8))
        self.executeProgramButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Ejecutar programa", None, QtGui.QApplication.UnicodeUTF8))
        self.generateEquivalentProgramButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Generar programa equivalente", None, QtGui.QApplication.UnicodeUTF8))
        self.unitTestRadioButton.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Unit Test", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Generar (el default es \"programa\"):", None, QtGui.QApplication.UnicodeUTF8))
        self.explorersTab.setTabText(self.explorersTab.indexOf(self.executionsTab), QtGui.QApplication.translate("BugReproducerAssistant", "Explorador de ejecuciones", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Output:", None, QtGui.QApplication.UnicodeUTF8))
        self.refreshProjectButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Refrescar proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.clearOutputButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Limpiar output", None, QtGui.QApplication.UnicodeUTF8))
        self.openProjectButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Abrir proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.newProjectButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Nuevo proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.closeProjectButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Cerrar proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.editProjectButton.setToolTip(QtGui.QApplication.translate("BugReproducerAssistant", "Abrir proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("BugReproducerAssistant", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("BugReproducerAssistant", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHerramientas.setTitle(QtGui.QApplication.translate("BugReproducerAssistant", "Herramientas", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewProject.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Nuevo Proyecto...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenProject.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Abrir Proyecto...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCloseProject.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Cerrar Proyecto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBraHelp.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Ayuda de Bug-reproducer Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Acerca de...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOptions.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Opciones...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditProject.setText(QtGui.QApplication.translate("BugReproducerAssistant", "Editar Proyecto...", None, QtGui.QApplication.UnicodeUTF8))

